Phase 1
olga-arkhipenko/beer-catalog pull request #1
Opened 2018-03-20 08:30 UTC by olga-arkhipenko

2018-03-21 08:16 UTC, ahryhoryeu requested changes
I liked your UI!
I didn't review paging algorithms thoroughly as well as webpack configuration. Please make sure they do conform other comments.

2018-03-21 08:16 UTC, ahryhoryeu commented on index.html
> +    <script src="./dist/bundle.js"></script>
Consider using non-filesystem paths like `/dist/bundle.js`.

2018-03-21 08:16 UTC, ahryhoryeu commented on package.json
> +        "npm": "^5.7.1",
Wat?

2018-03-21 08:16 UTC, ahryhoryeu commented on package.json
> +        "cross-env": "^5.1.3",
You don't seem to be using it, so please remove.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/App.vue
> +        <HeaderNavigation/>
Vue.js docs suggest (and I agree) using kebab-case for components in HTML, please refer to [the doc](https://vuejs.org/v2/guide/components.html#Component-Naming-Conventions).

2018-03-21 08:16 UTC, ahryhoryeu commented on src/api/PunkAPI.js
> +                  resolve(xhr.response);
To be more user-friendly, this method should return JS objects rather than JSON strings.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/api/PunkAPI.js
> +                  reject({
Rejecting is duplicated below.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/api/PunkAPI.js
> +                  status: this.status,
Avoid using `this` in such unclear places.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/Logo.vue
> +        logoName: 'Beer Catalog'
Seems like adding data for the sake of adding data. It's purely static, so I think it can be a part of the template. Then the `script` part can be omitted.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/api/utilities/UrlCreator.js
> +export default {
Consider making it more generic: it should receive the base URL as its parameter and ideally be ready to handle **route** parameters as well as **query** parameters.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/api/PunkAPI.js
> +    get(url) {
Consider providing more functions to cover `get`, `post`, `put`, and `delete` requests.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/Logo.vue
> +        <router-link to="/" href="/" class="link">
Are you sure you need an `href` attribute here?

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/Spinner.vue
> +<script>
Seems to me such dummy `script` tags can be omitted at all.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/catalog/AdvancedSearchPanel.vue
> +                    abv_gt: 2,
Consider giving meaningful names here and mapping later.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/catalog/AdvancedSearchPanel.vue
> +                this.$emit('submitSearch');
These two event seem to be tightened together. Is there any sense in separating them?

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/catalog/BeerCard.vue
> +            type: Object
In case of basic type checks you can just say `beer: Object`.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/catalog/BeerCard.vue
> +        addFavoriteBeerId(event, favoriteBeerId) {
Do you really have to accept `event` parameter here?

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/catalog/BeerCard.vue
> +            this.$emit('removeFavoriteBeer', favoriteBeerId);
It's debatable but it seems to me that methods here could dispatch the actions directly.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/catalog/BeerCard.vue
> +            this.$emit('removeFavoriteBeer', favoriteBeerId);
Also, consider making use of `mapState`, `mapMutations` and `mapActions` in such cases.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/store/store.js
> +        urlParams: {},
I can't express it precisely, but I don't like this state design. It seems that things like `urlParams`, `isFetched` and `isLoading` are not bound to live in state. At least I would recommend considering modules.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/store/store.js
> +            return state.beers.map(beer => ({
These mappers are half of the way to models! They do produce a defined model, the only thing is that it's not a class hence it's hard to track its shape.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/store/store.js
> +        SET_BEERS(state, beers) {
Poor naming detected. Notice how `SET_BEERS` and `SET_FAVORITE_BEERS` do essentially different things.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/store/store.js
> +        RESET_FAVORITE_BEERS(state) {
While resetting `beers` can be justified, I don't think it makes sense to remove already loaded favorite beers. Consider updating the code so that `favoriteBeers` is always in an up-to-date state.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/store/store.js
> +    actions: {
Consider splitting the file to have separate `actions.js` and `mutations.js` at least.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/catalog/Catalog.vue
> +        this.$store.commit('RESET_URL_PARAMS');
Consider introducing an action to avoid committing multiple mutations.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/catalog/Catalog.vue
> +            const pageHeight = document.documentElement.scrollHeight;
Consider moving such low-level mutation to separate helpers or utilities.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/catalog/SearchPanel.vue
> +        submitSearch() {
Most of the code in this method could and should be a part of an action. Do you really think this component couldn't just dispatch an action to perform search?

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/catalog/SearchPanel.vue
> +            this.$store.commit('RESET_URL_PARAMS');
Again, consider unifying a set of mutations into an action, or creating a special mutation that does several "atomic" operations.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/favorites/FavoriteBeerCard.vue
> +                <button class="action-button favorite-bar__button">OPEN</button>
Why suddenly CAPS here?

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/favorites/FavoriteBeerCard.vue
> +            this.$emit('removeFavoriteBeer', favoriteBeerId);
Again, it seems this could dispatch an action instead of emitting an event here.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/favorites/Favorites.vue
> +            :key=index
Why not `:key="beer.id"`?

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/favorites/FavoriteBeerCard.vue
> +    computed: {
Empty computed is totally redundant.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/favorites/Favorites.vue
> +            this.$store.commit('ADD_URL_PARAMS', { ...this.favoritesParams, ids: this.$store.state.favoriteBeerIds.join('|')});
Things like URL forming are too low-level for high-level components.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/favorites/Favorites.vue
> +            this.loadFavoriteBeers();
Chaining of actions can and should be done in actions themselves.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/favorites/Pagination.vue
> +        totalBeers: {
Pagination must be a very generic component that is not tightened to beers.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/header/HeaderNavigation.vue
> +import Logo from '../../components/Logo';
Consider introducing aliases to avoid relative paths.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/components/header/MainMenu.vue
> +            <ul class="main-menu__list">
It would be even better to have routes defined in some constant file and used for `vue-router` configuration and here to create menu items.

2018-03-21 08:16 UTC, ahryhoryeu commented on src/main.js
> +    render: h => h(App)
Consider using `components` property to initialize the app component. It seems there's no need to use render function here.

2018-03-21 13:15 UTC, olga-arkhipenko commented on package.json
> +        "npm": "^5.7.1",
accidentally, sorry
removed.

2018-03-21 13:16 UTC, olga-arkhipenko commented on package.json
> +        "cross-env": "^5.1.3",
removed.

2018-03-21 13:17 UTC, olga-arkhipenko commented on src/components/Logo.vue
> +        logoName: 'Beer Catalog'
no data here no more

2018-03-21 13:18 UTC, olga-arkhipenko commented on src/components/Logo.vue
> +        <router-link to="/" href="/" class="link">
no

2018-03-21 13:18 UTC, olga-arkhipenko commented on src/components/Spinner.vue
> +<script>
removed.

2018-03-21 13:23 UTC, olga-arkhipenko commented on src/components/catalog/BeerCard.vue
> +        addFavoriteBeerId(event, favoriteBeerId) {
no, I don't need it.
removed.

2018-03-21 13:25 UTC, olga-arkhipenko commented on src/components/favorites/FavoriteBeerCard.vue
> +                <button class="action-button favorite-bar__button">OPEN</button>
design drama
fixed.

2018-03-21 13:27 UTC, olga-arkhipenko commented on src/components/favorites/FavoriteBeerCard.vue
> +    computed: {
fully agree
deleted.

2018-03-21 13:34 UTC, olga-arkhipenko commented on src/components/favorites/Favorites.vue
> +            :key=index
improved.

2018-03-21 13:38 UTC, olga-arkhipenko commented on src/api/PunkAPI.js
> +                  reject({
fixed.

2018-03-21 13:45 UTC, olga-arkhipenko commented on src/api/PunkAPI.js
> +                  status: this.status,
modified.

2018-03-21 13:50 UTC, olga-arkhipenko commented on src/App.vue
> +        <HeaderNavigation/>
fixed.

2018-03-21 13:56 UTC, olga-arkhipenko commented on src/api/PunkAPI.js
> +                  resolve(xhr.response);
improved.

2018-03-22 09:02 UTC, olga-arkhipenko commented on index.html
> +    <script src="./dist/bundle.js"></script>
fixed.

2018-03-26 10:35 UTC, olga-arkhipenko commented on src/components/header/MainMenu.vue
> +            <ul class="main-menu__list">
done.

2018-03-26 10:35 UTC, olga-arkhipenko commented on src/main.js
> +    render: h => h(App)
done.

2018-03-27 15:47 UTC, olga-arkhipenko commented on src/components/favorites/Favorites.vue
> +            this.loadFavoriteBeers();
ok.

2018-03-27 16:01 UTC, olga-arkhipenko commented on src/components/favorites/Pagination.vue
> +        totalBeers: {
done.

2018-03-27 16:01 UTC, olga-arkhipenko commented on src/components/favorites/Favorites.vue
> +            this.$store.commit('ADD_URL_PARAMS', { ...this.favoritesParams, ids: this.$store.state.favoriteBeerIds.join('|')});
removed.

2018-03-27 16:02 UTC, olga-arkhipenko commented on src/components/catalog/Catalog.vue
> +            const pageHeight = document.documentElement.scrollHeight;
ok.

2018-03-28 09:40 UTC, olga-arkhipenko commented on src/api/utilities/UrlCreator.js
> +export default {
done.

2018-03-28 09:41 UTC, olga-arkhipenko commented on src/components/catalog/AdvancedSearchPanel.vue
> +                    abv_gt: 2,
done.

2018-03-28 09:41 UTC, olga-arkhipenko commented on src/components/catalog/AdvancedSearchPanel.vue
> +                this.$emit('submitSearch');
done.

2018-03-28 09:41 UTC, olga-arkhipenko commented on src/components/catalog/BeerCard.vue
> +            type: Object
ok.

2018-03-28 09:41 UTC, olga-arkhipenko commented on src/components/catalog/BeerCard.vue
> +            this.$emit('removeFavoriteBeer', favoriteBeerId);
done.

2018-03-28 09:42 UTC, olga-arkhipenko commented on src/store/store.js
> +        urlParams: {},
different modules now.

2018-03-28 09:42 UTC, olga-arkhipenko commented on src/store/store.js
> +            return state.beers.map(beer => ({
done.

2018-03-28 09:43 UTC, olga-arkhipenko commented on src/store/store.js
> +        SET_BEERS(state, beers) {
renamed.

2018-03-28 09:43 UTC, olga-arkhipenko commented on src/store/store.js
> +        RESET_FAVORITE_BEERS(state) {
removed.

2018-03-28 09:43 UTC, olga-arkhipenko commented on src/components/catalog/Catalog.vue
> +        this.$store.commit('RESET_URL_PARAMS');
fixed.

2018-03-28 09:43 UTC, olga-arkhipenko commented on src/components/catalog/SearchPanel.vue
> +            this.$store.commit('RESET_URL_PARAMS');
done.

2018-03-28 09:44 UTC, olga-arkhipenko commented on src/components/favorites/FavoriteBeerCard.vue
> +            this.$emit('removeFavoriteBeer', favoriteBeerId);
+

2018-03-28 09:44 UTC, olga-arkhipenko commented on src/components/header/HeaderNavigation.vue
> +import Logo from '../../components/Logo';
done.

2018-03-28 09:58 UTC, olga-arkhipenko commented on src/store/store.js
> +    actions: {
splitted.

2018-03-31 14:25 UTC, ahryhoryeu requested changes

2018-03-31 14:25 UTC, ahryhoryeu commented on src/App.vue
> +        'navigation': Navigation
So, after giving it a thought I came to a conclusion that it would be more straightforward to register the components as follows:
``` js
components: {
    Navigation,
    ...
}
```

2018-03-31 14:25 UTC, ahryhoryeu commented on src/App.vue
>      },
I would recommend avoiding trailing commas just as a styling piece of advice.

2018-03-31 14:25 UTC, ahryhoryeu commented on src/ajax/ajaxHelper.js
> +            const parsedData = JSON.parse(data);
It would be better to move `JSON.parse` to the thing that is responsible for sending AJAX requests and processing its results.

2018-03-31 14:25 UTC, ahryhoryeu commented on src/ajax/ajaxHelper.js
> +            const filteredData = dataUtils.catalogFilter(parsedData);
As we discussed, it should be replaced with a call to a `mapper` object that creates a corresponding object (or array of objects - think how to perform collection mappings in a generic way).

2018-03-31 14:25 UTC, ahryhoryeu commented on src/api/utilities/UrlCreator.js
> +export default {
Technically, neither of recommendations was done. Base URL is still here, route params (optional) do not get processed.

2018-03-31 14:25 UTC, ahryhoryeu commented on src/api/utilities/UrlCreator.js
> +                if(cur === 'beerIds') {
Checking for a very specific property is not generic at all.

2018-03-31 14:25 UTC, ahryhoryeu commented on src/components/cards/CatalogBeerCard.vue
>          isAddFavoriteButtonShown() {
What do you think of renaming it to `isFavoriteBeer`?

2018-03-31 14:25 UTC, ahryhoryeu commented on src/components/cards/FavoriteBeerCard.vue
> +            this.$emit('loadFavoriteBeerPage');
This emitting is incorrect. `FavoriteBeerCard` as a component knows nothing about pages and loading. All it has is one beer. It could emit an event that _a certain beer was removed from favorites_, but there's no need to do it. Reloading of the list can and should be handled by the action.

2018-03-31 14:25 UTC, ahryhoryeu commented on src/components/lists/GridList.vue
> +    <section class="grid-list">
Just a reminder about our conversation about generic lists and slots.

2018-03-31 14:25 UTC, ahryhoryeu commented on src/components/search/AdvancedSearchPanel.vue
> +                    <input type="range" min="4" max="80" class="advanced-search-panel__range" v-model.number="advancedSearchParams.colorByEBC" @change="submitSearch">
Consider introducing a `Slider` component that would encapsulate an input and a corresponding label.

2018-03-31 14:25 UTC, ahryhoryeu commented on src/components/search/AdvancedSearchPanel.vue
> +                    InterBitUnits: 0,
Inter Bit Units? Units that are placed between bits? 😆

2018-03-31 14:25 UTC, ahryhoryeu commented on src/components/catalog/AdvancedSearchPanel.vue
> +                this.$emit('submitSearch');
Done what? I see only some naming changes.

2018-03-31 14:25 UTC, ahryhoryeu commented on src/components/search/SearchPanel.vue
> +                this.resetStore();
This should be done in `search` action.

2018-03-31 14:25 UTC, ahryhoryeu commented on src/components/search/SearchPanel.vue
> +                this.$emit('loadBeerPage');
Avoid naming events after its handlers. The same works vice versa.

2018-03-31 14:25 UTC, ahryhoryeu commented on src/components/search/SearchPanel.vue
> +            this.resetStore();
Resetting store and page and so one should be handled by store and higher-level components. This one can emit a `searchReset` event in case it's really needed.

2018-03-31 14:25 UTC, ahryhoryeu commented on src/main.js
> +import store from './store/index';
Consider introducing aliases for `store` folder as well.

2018-03-31 14:25 UTC, ahryhoryeu commented on webpack.config.js
> +            {
Pay attention to formatting and indentation here.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/common/components/lists/GridList.vue
> +    <section class="grid-list">
Unfortunately, the list is still not doing the main thing it should be doing - enumeration! I mean, it lacks `v-for` and accepting some `items`.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/common/components/lists/RowList.vue
> +    <section class="row-list">
The same issue as for `GridList`.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/common/components/other/Pagination.vue
> +            <a
I would like to point out that this is semantically incorrect. Semantically it's a button, so this should be an appropriate tag.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/common/components/other/Pagination.vue
> +            this.$emit('pageChanged', pageNumber);
Have you seen the `.sync` modifier of `v-bind`? It seem to be its use-case. https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier

2018-04-03 15:52 UTC, ahryhoryeu commented on src/common/components/other/Pagination.vue
> +                :class="isActive(page)"
A super default example of how it should look like is:
```
<div v-bind:class="{ active: isActive }"></div>
```
It's better than having those names in JS.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/common/components/other/Pagination.vue
>              for (let i = this.pageRangeBefore; i <= this.pageRangeAfter; i++) {
It would be great to get rid of this ugly `for` loop. For example, by making use of smth like `[...Array(10).keys()]`.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/common/components/other/Slider.vue
> +            value: 0
Hm, I thought that `Slider` will get its value from a higher-level component.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/common/directives/pageScroll.js
> +        window.removeEventListener('scroll', handlePageBottom(binding.value));
This doesn't really remove the event listener.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/common/helpers/localStorageHelper.js
> +            window.localStorage.setItem(itemName, '[]');
This is not that generic, of course, because an empty array is not a default value for anything. But that's not paramount right now, so skip it.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/common/helpers/utilities/urlMapper.js
> +        return Object.keys(urlParams).reduce((accumulator, current) => {
It looks like semantically it's more like a `forEach` rather than `reduce` but that's debatable.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/features/favoritesManagement/store/index.js
>      namespaced: true,
To be more flexible, this module could not specify that it's necessarily namespaced. It could a responsibility of the module that includes this one.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/modules/catalog/components/AdvancedSearchPanel.vue
> +                @valueChanged="addAlcoholByVolume"
As I mentioned earlier, consider making use of `.sync`.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/modules/favorites/components/FavoritesCard.vue
> +            this.$emit('onFavoriteBeerRemove', favoriteBeerId);
As we discussed, the event should rather be called `favoriteBeerRemoved`.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/modules/favorites/components/FavoritesPage.vue
> +            @pageChanged="changePage"
Compare the name of the page here and in the `favorites-card` above. Do you see how inconsistent it is?

2018-04-03 15:52 UTC, ahryhoryeu commented on src/modules/favorites/components/FavoritesPage.vue
> +            this.removeFavoriteBeer({ id: favoriteBeerId, requestParams: this.pageParams });
It doesn't make much sense to me to map the action if it can't be called directly.

2018-04-03 15:52 UTC, ahryhoryeu commented on src/modules/favorites/services/favoritesService.js
> +        return ajaxHelper.get(url).then(beers => favoritesCardMapper.Map(JSON.parse(beers)));
I would argue that `JSON.parse` should be done in `ajaxHelper`.

2018-04-04 11:23 UTC, olga-arkhipenko commented on src/modules/favorites/services/favoritesService.js
> +        return ajaxHelper.get(url).then(beers => favoritesCardMapper.Map(JSON.parse(beers)));
done.

2018-04-04 11:25 UTC, olga-arkhipenko commented on src/modules/favorites/components/FavoritesCard.vue
> +            this.$emit('onFavoriteBeerRemove', favoriteBeerId);
fixed.

2018-04-04 11:27 UTC, olga-arkhipenko commented on src/modules/favorites/components/FavoritesPage.vue
> +            @pageChanged="changePage"
sorry...?

2018-04-04 11:28 UTC, olga-arkhipenko commented on src/common/components/other/Pagination.vue
> +            <a
fixed.

2018-04-04 11:37 UTC, olga-arkhipenko commented on src/common/helpers/localStorageHelper.js
> +            window.localStorage.setItem(itemName, '[]');
ok.

2018-04-04 11:38 UTC, olga-arkhipenko commented on src/features/favoritesManagement/store/index.js
>      namespaced: true,
ok.

2018-04-04 14:30 UTC, ahryhoryeu commented on src/modules/favorites/components/FavoritesPage.vue
> +            @pageChanged="changePage"
Name of the event I mean :)

2018-04-06 09:12 UTC, olga-arkhipenko commented on src/common/components/lists/GridList.vue
> +    <section class="grid-list">
done.

2018-04-06 09:12 UTC, olga-arkhipenko commented on src/common/components/lists/RowList.vue
> +    <section class="row-list">
done.

2018-04-06 09:13 UTC, olga-arkhipenko commented on src/common/components/other/Pagination.vue
> +                :class="isActive(page)"
fixed.

2018-04-06 09:13 UTC, olga-arkhipenko commented on src/common/directives/pageScroll.js
> +        window.removeEventListener('scroll', handlePageBottom(binding.value));
refactored.

2018-04-23 09:30 UTC, ahryhoryeu approved these changes
There are some changes suggested, but let's include them into phase 3.

2018-04-23 09:30 UTC, ahryhoryeu commented on src/common/components/other/Slider.vue
> +            this.$emit('update:value', this.value);
Consider introducing temp value variable to avoid the prop mutation.

2018-04-23 09:30 UTC, ahryhoryeu commented on src/common/directives/pageScroll.js
> +        el.__VueHandlePageBottom__ = handler;
While it's a way, Vue ideology says that a stateful binding should rather be a component.

2018-04-23 09:30 UTC, ahryhoryeu commented on src/common/helpers/ajaxHelper.js
> +    // get(url) {
Remove the comments. Switching back can easily be done with version control system - that what it's needed for.

2018-04-23 09:30 UTC, ahryhoryeu commented on src/common/helpers/ajaxHelper.js
> +        return fetch(url).then(response => response.json()).catch(alert);
I insist on a more generic `ajaxHelper`. This one can't do any requests except `GET`. You'll need `POST` and others in phase 3, that's the reason I've been insisting on that. So this can be done while working on phase-3.
But PLEASE do remove `alert` like ASAP. I'll pretend I didn't see it. Instead, make use of some notifications library to display fancy notifications.

2018-04-23 09:30 UTC, ahryhoryeu commented on src/common/helpers/localStorageHelper.js
>          window.localStorage.setItem(itemName, JSON.stringify(newItemData));
Ideally, this would be `Promise`-based as well.

2018-04-23 09:30 UTC, ahryhoryeu commented on src/common/services/beerService.js
> +        return ajaxHelper.get(url).then(beers => beers.map(beer => beerMapper.mapToBeer(beer)));
Can `beers.map(beer => beerMapper.mapToBeer(beer)` be replaced with `beers.map(beerMapper.mapToBeer)`?

2018-04-23 09:30 UTC, ahryhoryeu commented on src/common/utilities/urlCreator.js
> +        let fullPath = url;
Usually `let` is a sign of code that's not written so well. It seems to me, the method can be modified to avoid using `let`.

2018-04-23 09:30 UTC, ahryhoryeu commented on src/features/punkApiManagement/mappers/beerMapper.js
> +        brewingMapper.mapBrewing(beer.brewers_tips, beer.ingredients, beer.method);
Extra new line here.

2018-04-23 09:30 UTC, ahryhoryeu commented on src/modules/beerInfo/components/BeerInfoPage.vue
> +            v-cloak
So I see you setting this `v-cloak` directive all around the code, but there's no sign of you using it. Its usage should be combined with CSS, see examples: https://vuejs.org/v2/api/#v-cloak.

2018-04-23 09:30 UTC, ahryhoryeu commented on src/modules/beerInfo/components/FoodPairing.vue
> +                :key="index"
Note that using `index` as a key only works in case there are no reorderings. Ideally, you would use some `item.id` as a key.

2018-04-23 09:30 UTC, ahryhoryeu commented on src/modules/beerInfo/components/Ingredients.vue
> +                :key="index + Math.random()">
What? Why?

2018-04-23 09:30 UTC, ahryhoryeu commented on src/modules/beerInfo/services/beerDetailsService.js
> +        return ajaxHelper.get(url).then(beer => beerMapper.mapToBeerDetails(beer[0]));
Please make use of formatting with new lines.

2018-04-23 10:39 UTC, olga-arkhipenko commented on src/common/helpers/ajaxHelper.js
> +    // get(url) {
okey, it was added just for paying attention.

2018-04-23 12:38 UTC, olga-arkhipenko commented on src/modules/beerInfo/components/BeerInfoPage.vue
> +            v-cloak
sorry, forgot to add styling.
fixed now.

2018-04-23 13:18 UTC, olga-arkhipenko commented on src/common/services/beerService.js
> +        return ajaxHelper.get(url).then(beers => beers.map(beer => beerMapper.mapToBeer(beer)));
replaced.

2018-04-23 14:13 UTC, olga-arkhipenko commented on src/features/punkApiManagement/mappers/beerMapper.js
> +        brewingMapper.mapBrewing(beer.brewers_tips, beer.ingredients, beer.method);
okey.

2018-04-23 15:47 UTC, olga-arkhipenko commented on src/modules/beerInfo/components/FoodPairing.vue
> +                :key="index"
replaced indexes with item ids.

2018-04-23 15:48 UTC, olga-arkhipenko commented on src/modules/beerInfo/components/Ingredients.vue
> +                :key="index + Math.random()">
cleaned up this zashkvar.

2018-04-23 16:01 UTC, olga-arkhipenko commented on src/common/utilities/urlCreator.js
> +        let fullPath = url;
modified.

2018-04-23 16:02 UTC, merged

2018-04-24 09:43 UTC, olga-arkhipenko commented on src/modules/beerInfo/services/beerDetailsService.js
> +        return ajaxHelper.get(url).then(beer => beerMapper.mapToBeerDetails(beer[0]));
+

2018-04-24 13:14 UTC, olga-arkhipenko commented on src/common/helpers/localStorageHelper.js
>          window.localStorage.setItem(itemName, JSON.stringify(newItemData));
no problem.

2018-04-24 14:18 UTC, olga-arkhipenko commented on src/common/components/other/Slider.vue
> +            this.$emit('update:value', this.value);
success!